USE master
GO

DROP DATABASE ShowRunner
GO

CREATE DATABASE Showrunner
GO

USE Showrunner
GO

CREATE TABLE Network
(
Oid			INT IDENTITY(1,1) NOT NULL,
ApiId		INT,
[Name]		NVARCHAR(MAX),
CONSTRAINT PK_Network PRIMARY KEY (Oid),
)
GO

CREATE TABLE Genre
(
Oid				INT IDENTITY(1,1) NOT NULL,
[Description]	NVARCHAR(MAX),
CONSTRAINT PK_Genre PRIMARY KEY (Oid),
)
GO

CREATE TABLE Show
(
Oid			INT IDENTITY(1,1) NOT NULL,
ApiId		INT,
Title		NVARCHAR(MAX),
Rating		DECIMAL(10,2),
Premiered	DATETIME,
Summary		NVARCHAR(MAX),
Network		INT,
CONSTRAINT PK_Show PRIMARY KEY (Oid),
CONSTRAINT FK_Show_Network FOREIGN KEY (Network) REFERENCES Network(Oid),
)
GO

CREATE TABLE Episode
(
Oid			INT IDENTITY(1,1) NOT NULL,
Show		INT NOT NULL,
ApiId		INT,
Title		NVARCHAR(MAX),
Season		INT,
AirDate		DATETIME,
Summary		NVARCHAR(MAX),
Number		INT,
CONSTRAINT PK_Episode PRIMARY KEY (Oid),
CONSTRAINT FK_Episode_Show FOREIGN KEY (Show) REFERENCES Show(Oid)
)
GO

CREATE TABLE ShowGenre
(
Oid			INT IDENTITY(1,1) NOT NULL,
Genre		INT,
Show		INT,
CONSTRAINT PK_ShowGenre PRIMARY KEY (Oid),
CONSTRAINT UQ_ShowGenre UNIQUE NONCLUSTERED (Genre, Show)
)
GO